import 'package:kiwi/kiwi.dart';
import '../core/logic/dio_helper.dart';
import 'about_app/bloc.dart';
import 'active_acount/bloc.dart';
import 'add_address/bloc.dart';
import 'add_product_rate/bloc.dart';
import 'add_to_cart/bloc.dart';
import 'cancel_order/bloc.dart';
import 'comleting_order/bloc.dart';
import 'confirm_new_pass/bloc.dart';
import 'confirm_pass_code/bloc.dart';
import 'contact/bloc.dart';
import 'delete_address/bloc.dart';
import 'delete_from_cart/bloc.dart';
import 'edit_pass/bloc.dart';
import 'edit_profile/bloc.dart';
import 'faqs/bloc.dart';
import 'fav/bloc.dart';
import 'forget_pass/bloc.dart';
import 'get_addresses/bloc.dart';
import 'get_categories/bloc.dart';
import 'get_catigory_product/bloc.dart';
import 'get_cities/bloc.dart';
import 'get_order/bloc.dart';
import 'get_product/bloc.dart';
import 'home_slider/bloc.dart';
import 'is_fav/bloc.dart';
import 'login/bloc.dart';
import 'logout/bloc.dart';
import 'notifications/bloc.dart';
import 'privacy/bloc.dart';
import 'product_rate/bloc.dart';
import 'resend_code/bloc.dart';
import 'search/bloc.dart';
import 'show_cart/bloc.dart';
import 'sign_up/bloc.dart';
import 'suggestions/bloc.dart';
import 'update_item_cart_amount/bloc.dart';

void initKiwi() {
  final container = KiwiContainer();

  container.registerSingleton((c) => DioHelper());
  container.registerSingleton((c) => AboutAppBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => ActiveAccountBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => ConfirmNewPassBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => ConfirmPassCodeBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => EditProfileBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => ForgetPassBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => GetCitiesBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => ResendCodeBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => SignUpBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => LoginBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => HomeSliderBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => LogoutBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => CreateContactBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => PrivacyBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => CategoriesBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => GetProductsBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => AddToCartBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => GetAddressesBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => DeleteAddressesBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => AddAddressBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => GetFavBloc(c.resolve<DioHelper>()));
  container
      .registerFactory((c) => GetNotificationsBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => GetOrdersBloc(c.resolve<DioHelper>()));
  container
      .registerFactory((c) => GetCatigoryProductBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => GetProductRateBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => FAQsBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => GetContactBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => IsFavBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => ShowCartBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => DeleteFromCartBloc(c.resolve<DioHelper>()));
  container
      .registerFactory((c) => UpdateCartAmountBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => EditPassBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => AddProductRateBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => CancelOrderBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => CompletingOrderBloc(c.resolve<DioHelper>()));
  container.registerFactory((c) => SearchBloc(c.resolve<DioHelper>()));
}
